### ISSUE TITLE
Add total power house consumption

### ISSUE THREAD

**Issue by softwarebloat** [msx8020/ChargesplitHomeAssistant#1]
Thanks for this custom integration! it's great!
considering chargesplit it is able to read the house power consumption to balance the load of car charges, would be cool to have the total power consumption (kWh) to be used in home assistant energy tab to have the total consumed energy from the grid (even though it's probably not so accurate in a three phase system).

so reading the code i think something like this should be added in `sensor.py`:
```py
(
    "total_power_house_power",
    "Total House Consumption",
    "TOTALHOUSEPWR",
    UnitOfEnergy.KILO_WATT_HOUR,
    "mdi:speedometer",
    SensorDeviceClass.ENERGY,
    SensorStateClass.TOTAL_INCREASING,
    serial,
)
```
but i think that's not enough to register the entity as i tried in my instance and i can see it now but it's unavailable:
![image](https://github.com/user-attachments/assets/35e38f69-a30f-450e-be4e-0e76687d3f31)
i guess that needs to be fetched from the api probably

so as i said, would be a nice to have it to be able to add it here as a source:
![image](https://github.com/user-attachments/assets/d7094a1f-3463-41ff-ab01-2b398f273415)

**Comment by softwarebloat** [comment]
i've been privately contacted by Chargesplit Customer Service and i made a few tests.
i believe the Chargeslipt API should return that value with the new key ((e.g.: "TOTALHOUSEPWR" ) so that home assistant can use it.

**Comment by softwarebloat** [comment]
hey, is it possible to add this? 🙏

**Comment by msx8020** [comment]
Hello,  We're are evaluating the proposal. 

The counter is actually not made on wallbox side but is aggregated on sever side and require time to decide best approach ( probably a new TOTAL_INCREASING variable ) to be exposed 

please be patience as we look for a solution

Best Regards

**Comment by softwarebloat** [comment]
Yes I imagined that. Thank you!

**Comment by msx8020** [comment]
hello, 
components has been updated with the 2 measurement for house and solar generation 

please update it
